Add workflow for RDP-INSTANCE-1

diff --git a/.github/workflows/RDP-INSTANCE-1.yml b/.github/workflows/RDP-INSTANCE-1.yml
--- a/.github/workflows/RDP-INSTANCE-1.yml
+++ b/.github/workflows/RDP-INSTANCE-1.yml
@@ -84,11 +84,11 @@ jobs:
           echo "CLOUD_RDP_URL=$TMATE_SSH" >> $GITHUB_ENV
           
           # Report back to backend
-          if [ ! -z "7bec01dc-8dcf-4c29-8b02-25356b728e39" ]; then
+          if [ ! -z "501ff079-1935-491a-af36-05e319bc98b6" ]; then
             echo "Reporting to http://localhost:8000..."
             # URL encode the SSH string for curl
             ENCODED_SSH=$(echo $TMATE_SSH | sed 's/@/%40/g')
-            curl -X POST "http://localhost:8000/instance/7bec01dc-8dcf-4c29-8b02-25356b728e39/report?ip_address=$ENCODED_SSH" || echo "Report failed, but continuing..."
+            curl -X POST "http://localhost:8000/instance/501ff079-1935-491a-af36-05e319bc98b6/report?ip_address=$ENCODED_SSH" || echo "Report failed, but continuing..."
           fi
           
           echo "------------------------------------------"
